@file:Suppress("UNUSED_EXPRESSION")
@file:Title("Program Windows")
@file:ParentTitle("Interaction")
@file:Order("110")
@file:URL("interaction/programWindows")

package docs.`07_Interaction`

import org.openrndr.application
import org.openrndr.dokgen.annotations.*
import org.openrndr.math.IntVector2


fun main() {
    @Text
    """
    # Program windows
    An OPENRNDR program can listen to events generated by its window.

    ## Window properties

    ### Window title

    The window title can be set and read using the `title` property.
    """

    @Code
    application {
        configure {
            title = "Lo and behold!"
        }

        program {
            println(window.title)
        }
    }


    @Text
    """
    ### Window position

    The window position can be read and set using the `position` property.
    """

    @Code
    application {
        configure {
            position = IntVector2(30, 30)
        }
    }


    @Text
    """
    ## Window events

    ### Window move event

    This event is generated when the window was moved.
    """

    @Code
    application {
        program {
            window.moved.listen {
                println("the window was moved")
            }
        }
    }


    @Text
    """
    ### Window size event

    This event is generated when the window was sized.
    """

    @Code
    application {
        program {
            window.sized.listen {
                println("the window was sized")
            }
        }
    }


    @Text
    """
    ### Window focus event

    This event is generated when the program window gains focus.
    """

    @Code
    application {
        program {
            window.focused.listen {
                println("the window has gained focus")
            }
        }
    }


    @Text
    """
    ### Window unfocus event

    This event is generated when the program window loses focus.
    """

    @Code
    application {
        program {
            window.unfocused.listen {
                println("the window has lost its focus")
            }
        }
    }
}