name: Build Guide PDF

on:
  page_build: # Triggers after GitHub Pages finishes building / deploying

  # Allow manual trigger
  workflow_dispatch:

jobs:
  post-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Download full guide website
        run: wget --mirror --reject "*.mp4" --page-requisites --convert-links -P ./ https://guide.openrndr.org/

      - name: Build PDF guide
        uses: jensvog/ebook-convert-action@v1
        if: always()
        with:
          in: guide.openrndr.org/index.html
          out: openrndr-guide.pdf
          args: --paper-size a4 --pdf-default-font-size 12 --pdf-mono-font-size 12 --chapter / --page-breaks-before / --chapter-mark none --pdf-page-margin-bottom 36 --pdf-page-margin-top 36 --pdf-page-margin-left 36 --pdf-page-margin-right 36 --pretty-print

      - name: Update pdf branch
        run: |
          git worktree add --detach pdf-temp
          cd pdf-temp
          git checkout --orphan pdf
          git reset HEAD -- .
          git clean -df
          mv /github/workspace/openrndr-guide.pdf .
          git status
          git config --global user.email "actions@openrndr.org"
          git config --global user.name "OPENRNDR Actions"
          git add .
          git commit -m "Add automatically generated PDF guide"
          git push origin pdf --force

