# Builds the guide without producing screenshots or video files
name: Quick build
on:
  # Trigger the workflow on any pull request
  pull_request:

  push:
    branches:
      - main
  
  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Test glxinfo
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb
          xvfb-run glxinfo

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build openrndr-guide
        run: skipMediaGeneration=true xvfb-run ./gradlew dokgen

