name: Publish guide online
on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+-[0-9]+
  
  # Allow manual trigger
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Test glxinfo
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb
          xvfb-run glxinfo

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Build openrndr-guide
        run: skipMediaGeneration=false xvfb-run ./gradlew dokgen

      - name: Publish guide
        run: |
          git worktree add --detach docs-temp
          cd docs-temp
          git checkout --orphan generated
          git reset HEAD -- .
          git clean -df
          rm -rf ../build/dokgen/jekyll/docs/_site
          rm -rf ../build/dokgen/jekyll/docs/webServer*
          rm -rf ../build/dokgen/jekyll/docs/.jekyll-cache
          mv ../build/dokgen/jekyll/* .
          git status
          git config --global user.email "actions@openrndr.org"
          git config --global user.name "OPENRNDR Actions"
          git add . 
          git commit -m "Add automatically generated guide"
          git push origin generated --force          
